homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 26
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

#device_tracker: !include_dir_merge_list device_trackers
device_tracker:
  - platform: nmap_tracker
    hosts: #!secret nmap_tracker_ip
      - 10.0.0.8
      - 10.0.0.15
    interval_seconds: 30
    #track_new_devices: no

hassio:

#ios:

switch:
  - platform: tplink
    host: !secret tplink_switch_ip

zwave:
  usb_path: /dev/ttyACM0

ifttt:
  key: !secret ifttt_key

nest:
  client_id: !secret nest_product_id
  client_secret: !secret nest_product_secret

arlo:
  username: !secret my_username
  password: !secret arlo_password

ring:
  username: !secret my_username
  password: !secret ring_password

camera: !include camera.yaml

http:
  api_password: !secret hassio_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret hassio_base_url
  #login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
group: !include groups.yaml
automation: !include automations.yaml
#script: !include_dir_merge_named script
script: !include scripts.yaml
