############################################################
#
# Nest Sensor
#
############################################################

- platform: nest
  monitored_conditions:
    - ‘weather_temperature’
    - ‘weather_humidity’
    - ‘weather_condition’
    - ‘wind_speed’
    - 'target'
    - 'temperature'
    - 'humidity'
    - 'co_status'
    - 'smoke_status'
    - 'battery_health'
